### ISSUE TITLE
binary_sensor and mediaplayer problem

### ISSUE THREAD

**Issue by cryptooth** [pkozul/ha-floorplan-kiosk#6]
Binary sensors and media player are displaying in dev-states page on hass.io. But I can't get any motion or plugged states from fully kiosk tablet. 

Here is my floorplan.yaml

```
      name: Floorplan
      image: /local/custom_ui/floorplan/floorplan.svg
      stylesheet: /local/custom_ui/floorplan/floorplan.css

      warnings:
      debug:
      fully_kiosk:

      devices:
        - name: Entry Kiosk
          address: 70:72:0d:b0:83:74
          motion_sensor: binary_sensor.entry_kiosk_motion
          plugged_sensor: binary_sensor.entry_kiosk_plugged
          media_player: media_player.entry_kiosk

```

any advice?

**Comment by grewhit25** [comment]
That part of your config is not enough to figure out what's gone wrong because the binary sensors are declared elsewhere  in home-assistant. Enabling debug is also useful.

Here is a working example from my packaged config: Hope it helps.

``` yaml
# https://github.com/pkozul/ha-floorplan-kiosk
# fully-kiosk package configuration for my fire tablet
# Using fire OS version 1.25.1
# https://www.ozerov.de/fully-kiosk-browser/files/2018/06/Fully-Kiosk-Browser-v1.25.1-fire.apk

homeassistant:
  customize:
    sensor.entry_kiosk_screen:
      custom_ui_state_card: state-card-floorplan
      config:
        config: /local/custom_ui/floorplan/floorplan.yaml
    
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html

# For each Fully Kiosk device, create a binary / sensor entity:
sensor:

# https://community.home-assistant.io/t/fully-kiosk-browser/41675/39
# Experimenting with Rest sensor to control the device

#  - platform: rest
#    name: entry_kiosk Rest Sensor
#    json_attributes:
#      - batteryLevel
#      - kioskMode
#      - screenBrightness
#      - motionDetectorState
#      - maintenanceMode
#      - appFreeMemory
#      - appUsedMemory
#      - totalFreeMemory
#      - totalUsedMemory
#      - hostname4
#      - ip4
#      - mac
#      - locationLatitude
#      - locationLongitude
#      - locationAltitude
#      - startUrl
#      - currentPage
#    resource: !secret entry_kiosk_key
#    value_template: "{{ value_json.isScreenOn }}"
    
# You can extract the device battery state like this      
  - platform: template
    sensors:
      entry_kiosk_battery:
        friendly_name: "entry_kiosk Battery"
        unit_of_measurement: '%'
        value_template: "{{ states.binary_sensor.entry_kiosk_motion.attributes.battery_level }}"

# This sensor is for use with state card, trigger fully-kiosy from the tablet.      
      entry_kiosk_screen:
        friendly_name: 'entry_kiosk Screen'
        value_template: "{{ 'Online' if (states.binary_sensor.entry_kiosk_motion.attributes._isScreenOn) else 'Off' }}"         

binary_sensor: 

  - platform: mqtt
    state_topic: floorplan/kiosk/entry_kiosk_motion
    name: entry_kiosk Motion
    device_class: motion
    retain: true

  - platform: mqtt
    state_topic: floorplan/kiosk/entry_kiosk_plugged
    name: entry_kiosk Plugged
    device_class: Plug
    retain: true

light:
  - platform: mqtt_json
    name: entry_kiosk Screensaver
    state_topic: floorplan/entry_kiosk_screensaver
    command_topic: floorplan/entry_kiosk_screensaver/set
    brightness: true
                   
# For each Fully Kiosk device, create a media player entity:
media_player:
  - platform: floorplan_speaker
    name: entry_kiosk Speaker

# display using state card
group:
  floorplan:
    entities:
#      - sensor.entry_kiosk_screen
      - sensor.entry_kiosk_battery
      - binary_sensor.entry_kiosk_motion
      - binary_sensor.entry_kiosk_plugged

# display using panel

#panel_custom:
#  - name: floorplan
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:home
#    url_path: floorplan
#    config:
#      hide_app_toolbar:
#      config: /local/custom_ui/floorplan/floorplan.yaml

#  - name: clock
#    sidebar_title: Alarm Clock
#    sidebar_icon: mdi:alarm
#    url_path: clock
#    config:
#      hide_app_toolbar:
#      config: /local/custom_ui/floorplan/alarm_clock.yaml
```
